// packages/cli/templates/vue/src/components/AIPanel.vue
<script setup lang="ts">
import { computed, nextTick, ref } from 'vue';
import { AI, type Message, type ModelInfo } from '@nearstack-dev/ai';
import type { Note } from '../models/Note';

const props = defineProps<{ notes: Note[]; ai: AI }>();

const input = ref('');
const messages = ref<Message[]>([]);
const isSending = ref(false);
const error = ref('');
const bottomEl = ref<HTMLDivElement>();
const models = ref<ModelInfo[]>(props.ai.models.list());
const selectedModel = ref(props.ai.models.active()?.id ?? '');
const isDownloading = ref(false);
const downloadProgress = ref(0);

const selectedModelInfo = computed(() => models.value.find(m => m.id === selectedModel.value));
const selectedModelError = computed(() => {
  const status = selectedModelInfo.value?.status;
  return status?.state === 'error' ? status.message : null;
});
const needsSetup = computed(() => {
  const m = selectedModelInfo.value;
  return !m || (m.status.state !== 'cached' && m.status.state !== 'ready');
});

function buildSystemPrompt(): string | undefined {
  if (props.notes.length === 0) return undefined;
  const summary = props.notes
    .sort((a, b) => b.updatedAt - a.updatedAt)
    .slice(0, 20)
    .map(n => {
      const tags = n.tags.length ? ` [${n.tags.join(', ')}]` : '';
      return `- "${n.title || 'Untitled'}"${tags}: ${n.content.slice(0, 200)}`;
    })
    .join('\n');
  return [
    'You are a helpful AI assistant in a personal notes app.',
    `The user has ${props.notes.length} notes:`,
    summary,
    'Be concise. Reference note titles when relevant.',
  ].join('\n\n');
}

async function selectModelAndDownload() {
  if (isDownloading.value) return;
  if (!selectedModel.value) return;
  const model = models.value.find(m => m.id === selectedModel.value);
  if (!model) return;

  // 'error' state needs a fresh download too — otherwise a failed download
  // leaves the model unusable until reload.
  const needsDownload =
    model.status.state === 'available' || model.status.state === 'error';

  if (needsDownload) {
    isDownloading.value = true;
    downloadProgress.value = 0;
    const unsub = props.ai.subscribe(state => {
      if (state.downloading?.modelId === selectedModel.value) {
        downloadProgress.value = state.downloading.progress;
      }
    });
    try {
      await props.ai.models.download(selectedModel.value);
    } finally {
      unsub();
      isDownloading.value = false;
      models.value = props.ai.models.list();
    }
  }

  // Only activate if the model is now ready/cached. After a failed download
  // we'd otherwise reach use() with status 'error' and throw.
  const refreshed = props.ai.models.get(selectedModel.value);
  if (refreshed?.status.state === 'cached' || refreshed?.status.state === 'ready') {
    await props.ai.models.use(selectedModel.value);
  }
  models.value = props.ai.models.list();
}

async function send() {
  const text = input.value.trim();
  if (!text) return;
  input.value = '';
  error.value = '';
  const next: Message[] = [...messages.value, { role: 'user', content: text }];
  messages.value = next;
  isSending.value = true;
  try {
    const systemPrompt = buildSystemPrompt();
    const apiMessages: Message[] = systemPrompt
      ? [{ role: 'system', content: systemPrompt }, ...next]
      : next;
    const reply = await props.ai.chat(apiMessages);
    messages.value = [...next, { role: 'assistant', content: reply }];
  } catch (e) {
    error.value = e instanceof Error ? e.message : 'Chat failed';
  } finally {
    isSending.value = false;
    await nextTick();
    bottomEl.value?.scrollIntoView({ behavior: 'smooth' });
  }
}

function clear() {
  messages.value = [];
  error.value = '';
}
</script>

<template>
  <div class="flex h-full flex-col">
    <div class="flex items-center justify-between border-b border-neutral-200 px-4 py-2">
      <h2 class="text-sm font-semibold">AI Assistant</h2>
      <button v-if="messages.length > 0" @click="clear" class="text-xs text-neutral-400 hover:text-black">Clear</button>
    </div>

    <div v-if="needsSetup" class="flex flex-1 flex-col items-center justify-center p-6 text-center">
      <p class="text-sm font-medium">Set up a local AI model</p>
      <p class="mt-1 text-xs text-neutral-500">Models run entirely on your device. No data leaves your browser.</p>
      <select
        v-model="selectedModel"
        class="mt-4 w-full border border-neutral-300 bg-white px-3 py-2 text-sm focus:border-black focus:outline-none"
        :disabled="isDownloading"
      >
        <option value="">Select a model</option>
        <option v-for="m in models" :key="m.id" :value="m.id">{{ m.provider }} &middot; {{ m.name }}</option>
      </select>
      <button
        v-if="selectedModelInfo?.status.state === 'available'"
        @click="selectModelAndDownload"
        class="mt-3 w-full bg-black px-3 py-2 text-sm text-white hover:bg-neutral-800"
      >
        Download model
      </button>
      <div v-if="isDownloading" class="mt-3 w-full">
        <div class="h-1 w-full overflow-hidden bg-neutral-200">
          <div class="h-full bg-black transition-all" :style="{ width: `${Math.round(downloadProgress * 100)}%` }" />
        </div>
        <p class="mt-1 text-xs text-neutral-500">Downloading {{ Math.round(downloadProgress * 100) }}%</p>
      </div>
      <div v-if="selectedModelError" class="mt-3 w-full">
        <p class="text-xs text-red-600">{{ selectedModelError }}</p>
        <button
          @click="selectModelAndDownload"
          :disabled="isDownloading"
          class="mt-2 w-full bg-black px-3 py-2 text-sm text-white hover:bg-neutral-800 disabled:opacity-50"
        >
          Retry download
        </button>
      </div>
    </div>

    <template v-else>
      <div class="flex-1 overflow-y-auto p-4">
        <div v-if="messages.length === 0" class="flex h-full items-center justify-center text-center text-neutral-400">
          <div>
            <p class="text-sm font-medium">Ask about your notes</p>
            <div class="mt-3 space-y-1.5 text-xs text-neutral-500">
              <p>&ldquo;Summarize my recent notes&rdquo;</p>
              <p>&ldquo;What topics come up most?&rdquo;</p>
              <p>&ldquo;Help me draft a note about...&rdquo;</p>
            </div>
          </div>
        </div>
        <div class="space-y-3">
          <div
            v-for="(msg, i) in messages"
            :key="`${msg.role}-${i}`"
            :class="['text-sm', msg.role === 'assistant' ? 'text-neutral-700' : 'ml-8 bg-neutral-100 px-3 py-2']"
          >
            {{ msg.content }}
          </div>
          <p v-if="error" class="text-xs text-red-600">{{ error }}</p>
        </div>
        <div ref="bottomEl" />
      </div>
      <form @submit.prevent="send" class="border-t border-neutral-200 p-3">
        <div class="flex gap-2">
          <input
            v-model="input"
            placeholder="Ask anything..."
            class="flex-1 border border-neutral-300 bg-white px-3 py-2 text-sm placeholder:text-neutral-400 focus:border-black focus:outline-none"
          />
          <button
            type="submit"
            :disabled="isSending"
            class="bg-black px-3 py-2 text-sm text-white hover:bg-neutral-800 disabled:opacity-50"
          >
            Send
          </button>
        </div>
      </form>
    </template>
  </div>
</template>

// packages/cli/templates/react/src/components/AIPanel.tsx
import { useEffect, useMemo, useRef, useState } from 'react';
import Markdown from 'react-markdown';
import { useChat, useModelSelector } from '@nearstack-dev/react/ai';
import type { Note } from '../models/Note';

interface AIPanelProps {
  notes: Note[];
}

function buildSystemPrompt(notes: Note[]): string | undefined {
  if (notes.length === 0) return undefined;

  const notesSummary = notes
    .sort((a, b) => b.updatedAt - a.updatedAt)
    .slice(0, 20)
    .map(note => {
      const tags = note.tags.length > 0 ? ` [${note.tags.join(', ')}]` : '';
      return `- "${note.title || 'Untitled'}"${tags}: ${note.content.slice(0, 200)}`;
    })
    .join('\n');

  return [
    'You are a helpful AI assistant integrated into a personal notes app.',
    "You have access to the user's notes and can help find information, summarize content, suggest connections between notes, and answer questions.",
    `The user has ${notes.length} notes. Here are the most recent:`,
    notesSummary,
    'Be concise and helpful. Reference specific notes by title when relevant.',
  ].join('\n\n');
}

export function AIPanel({ notes }: AIPanelProps) {
  const [input, setInput] = useState('');
  const bottomRef = useRef<HTMLDivElement>(null);
  const systemPrompt = useMemo(() => buildSystemPrompt(notes), [notes]);
  const { messages, send, isStreaming, error, clear } = useChat(undefined, { systemPrompt });
  const {
    choices,
    selectModel,
    downloadModel,
    isDownloading,
    downloadProgress,
    currentSelection,
    selectedModel,
  } = useModelSelector();

  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages]);

  const needsSetup =
    !selectedModel ||
    (selectedModel.status?.state !== 'cached' && selectedModel.status?.state !== 'ready');

  return (
    <div className="flex h-full flex-col">
      <div className="flex items-center justify-between border-b border-neutral-200 px-4 py-2">
        <h2 className="text-sm font-semibold">AI Assistant</h2>
        {messages.length > 0 && (
          <button onClick={clear} className="text-xs text-neutral-400 hover:text-black">
            Clear
          </button>
        )}
      </div>

      {needsSetup ? (
        <div className="flex flex-1 flex-col items-center justify-center p-6 text-center">
          <p className="text-sm font-medium">Set up a local AI model</p>
          <p className="mt-1 text-xs text-neutral-500">
            Models run entirely on your device. No data leaves your browser.
          </p>

          <select
            className="mt-4 w-full border border-neutral-300 bg-white px-3 py-2 text-sm focus:border-black focus:outline-none"
            value={currentSelection ?? ''}
            onChange={e => {
              if (e.target.value) void selectModel(e.target.value);
            }}
            disabled={isDownloading}
          >
            <option value="">Select a model</option>
            {choices.map(choice => (
              <option key={choice.value} value={choice.value} disabled={choice.disabled}>
                {choice.group} &middot; {choice.label}
              </option>
            ))}
          </select>

          {selectedModel?.status?.state === 'available' && (
            <button
              onClick={() => void downloadModel(selectedModel.id)}
              className="mt-3 w-full bg-black px-3 py-2 text-sm text-white hover:bg-neutral-800"
            >
              Download model
            </button>
          )}

          {isDownloading && (
            <div className="mt-3 w-full">
              <div className="h-1 w-full overflow-hidden bg-neutral-200">
                <div
                  className="h-full bg-black transition-all"
                  style={{ width: `${Math.round(downloadProgress * 100)}%` }}
                />
              </div>
              <p className="mt-1 text-xs text-neutral-500">
                Downloading {Math.round(downloadProgress * 100)}%
              </p>
            </div>
          )}

          {selectedModel?.status?.state === 'error' && (
            <p className="mt-2 text-xs text-red-600">{selectedModel.status.message}</p>
          )}
        </div>
      ) : (
        <>
          <div className="flex-1 overflow-y-auto p-4">
            {messages.length === 0 && (
              <div className="flex h-full items-center justify-center">
                <div className="text-center text-neutral-400">
                  <p className="text-sm font-medium">Ask about your notes</p>
                  <div className="mt-3 space-y-1.5 text-xs">
                    <p className="text-neutral-500">&ldquo;Summarize my recent notes&rdquo;</p>
                    <p className="text-neutral-500">&ldquo;What topics come up most?&rdquo;</p>
                    <p className="text-neutral-500">&ldquo;Help me draft a note about...&rdquo;</p>
                  </div>
                </div>
              </div>
            )}

            <div className="space-y-3">
              {messages.map((message, index) => (
                <div
                  key={`${message.role}-${index}`}
                  className={`text-sm ${
                    message.role === 'assistant'
                      ? 'prose prose-sm prose-neutral max-w-none'
                      : 'ml-8 bg-neutral-100 px-3 py-2'
                  }`}
                >
                  {message.role === 'assistant' ? (
                    <Markdown>{message.content}</Markdown>
                  ) : (
                    message.content
                  )}
                </div>
              ))}
              {error && <p className="text-xs text-red-600">{error}</p>}
            </div>
            <div ref={bottomRef} />
          </div>

          <form
            className="border-t border-neutral-200 p-3"
            onSubmit={async e => {
              e.preventDefault();
              const value = input.trim();
              if (!value) return;
              setInput('');
              await send(value);
            }}
          >
            <div className="flex gap-2">
              <input
                value={input}
                onChange={e => setInput(e.target.value)}
                placeholder="Ask anything..."
                className="flex-1 border border-neutral-300 bg-white px-3 py-2 text-sm placeholder:text-neutral-400 focus:border-black focus:outline-none"
              />
              <button
                type="submit"
                disabled={isStreaming}
                className="bg-black px-3 py-2 text-sm text-white hover:bg-neutral-800 disabled:opacity-50"
              >
                Send
              </button>
            </div>
          </form>
        </>
      )}
    </div>
  );
}
