// packages/cli/templates/svelte/src/App.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { TodoModel, type Todo } from './models/Todo';

  let todos: Todo[] = [];
  let newTodoTitle = '';

  onMount(async () => {
    await loadTodos();
  });

  async function loadTodos() {
    todos = await TodoModel.table().getAll();
  }

  async function addTodo(e: Event) {
    e.preventDefault();
    if (!newTodoTitle.trim()) return;

    const newTodo = await TodoModel.table().insert({
      title: newTodoTitle,
      completed: false,
      createdAt: Date.now(),
    });

    todos = [...todos, newTodo];
    newTodoTitle = '';
  }

  async function toggleTodo(id: string) {
    const todo = todos.find((t) => t.id === id);
    if (!todo) return;

    const updated = await TodoModel.table().update(id, {
      completed: !todo.completed,
    });

    if (updated) {
      todos = todos.map((t) => (t.id === id ? updated : t));
    }
  }

  async function deleteTodo(id: string) {
    await TodoModel.table().delete(id);
    todos = todos.filter((t) => t.id !== id);
  }

  $: remaining = todos.filter((t) => !t.completed).length;
</script>

<div class="app">
  <h1>Nearstack Todo App</h1>
  <p class="subtitle">Local-first, powered by @nearstack-dev/core</p>

  <form on:submit={addTodo} class="todo-form">
    <input
      type="text"
      bind:value={newTodoTitle}
      placeholder="What needs to be done?"
      class="todo-input"
    />
    <button type="submit" class="add-button">Add</button>
  </form>

  <div class="todo-list">
    {#if todos.length === 0}
      <p class="empty-state">No todos yet. Add one above!</p>
    {:else}
      {#each todos as todo (todo.id)}
        <div class="todo-item">
          <input
            type="checkbox"
            checked={todo.completed}
            on:change={() => toggleTodo(todo.id)}
            class="todo-checkbox"
          />
          <span class="todo-title" class:completed={todo.completed}>
            {todo.title}
          </span>
          <button on:click={() => deleteTodo(todo.id)} class="delete-button">
            Delete
          </button>
        </div>
      {/each}
    {/if}
  </div>

  <div class="stats">
    <span>{remaining} remaining</span>
    <span>{todos.length} total</span>
  </div>
</div>

<style>
  .app {
    max-width: 600px;
    margin: 0 auto;
    padding: 2rem;
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen,
      Ubuntu, Cantarell, sans-serif;
  }

  h1 {
    margin: 0 0 0.5rem;
    color: #333;
  }

  .subtitle {
    margin: 0 0 2rem;
    color: #666;
    font-size: 0.9rem;
  }

  .todo-form {
    display: flex;
    gap: 0.5rem;
    margin-bottom: 2rem;
  }

  .todo-input {
    flex: 1;
    padding: 0.75rem;
    font-size: 1rem;
    border: 2px solid #e0e0e0;
    border-radius: 4px;
  }

  .todo-input:focus {
    outline: none;
    border-color: #4a90e2;
  }

  .add-button {
    padding: 0.75rem 1.5rem;
    font-size: 1rem;
    background: #4a90e2;
    color: white;
    border: none;
    border-radius: 4px;
    cursor: pointer;
  }

  .add-button:hover {
    background: #357abd;
  }

  .todo-list {
    margin-bottom: 1rem;
  }

  .empty-state {
    text-align: center;
    color: #999;
    padding: 2rem;
  }

  .todo-item {
    display: flex;
    align-items: center;
    gap: 0.75rem;
    padding: 1rem;
    background: #f9f9f9;
    border-radius: 4px;
    margin-bottom: 0.5rem;
  }

  .todo-checkbox {
    width: 20px;
    height: 20px;
    cursor: pointer;
  }

  .todo-title {
    flex: 1;
    font-size: 1rem;
  }

  .todo-title.completed {
    text-decoration: line-through;
    color: #999;
  }

  .delete-button {
    padding: 0.5rem 1rem;
    font-size: 0.875rem;
    background: #e74c3c;
    color: white;
    border: none;
    border-radius: 4px;
    cursor: pointer;
  }

  .delete-button:hover {
    background: #c0392b;
  }

  .stats {
    display: flex;
    justify-content: space-between;
    color: #666;
    font-size: 0.875rem;
    padding-top: 1rem;
    border-top: 1px solid #e0e0e0;
  }
</style>

// packages/cli/templates/react/src/App.tsx
import { useState, useEffect } from 'react';
import { TodoModel, type Todo } from './models/Todo';
import './App.css';

function App() {
  const [todos, setTodos] = useState<Todo[]>([]);
  const [newTodoTitle, setNewTodoTitle] = useState('');

  useEffect(() => {
    loadTodos();
  }, []);

  const loadTodos = async () => {
    const allTodos = await TodoModel.table().getAll();
    setTodos(allTodos);
  };

  const addTodo = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!newTodoTitle.trim()) return;

    const newTodo = await TodoModel.table().insert({
      title: newTodoTitle,
      completed: false,
      createdAt: Date.now(),
    });

    setTodos([...todos, newTodo]);
    setNewTodoTitle('');
  };

  const toggleTodo = async (id: string) => {
    const todo = todos.find((t) => t.id === id);
    if (!todo) return;

    const updated = await TodoModel.table().update(id, {
      completed: !todo.completed,
    });

    if (updated) {
      setTodos(todos.map((t) => (t.id === id ? updated : t)));
    }
  };

  const deleteTodo = async (id: string) => {
    await TodoModel.table().delete(id);
    setTodos(todos.filter((t) => t.id !== id));
  };

  return (
    <div className="app">
      <h1>Nearstack Todo App</h1>
      <p className="subtitle">Local-first, powered by @nearstack-dev/core</p>

      <form onSubmit={addTodo} className="todo-form">
        <input
          type="text"
          value={newTodoTitle}
          onChange={(e) => setNewTodoTitle(e.target.value)}
          placeholder="What needs to be done?"
          className="todo-input"
        />
        <button type="submit" className="add-button">
          Add
        </button>
      </form>

      <div className="todo-list">
        {todos.length === 0 ? (
          <p className="empty-state">No todos yet. Add one above!</p>
        ) : (
          todos.map((todo) => (
            <div key={todo.id} className="todo-item">
              <input
                type="checkbox"
                checked={todo.completed}
                onChange={() => toggleTodo(todo.id)}
                className="todo-checkbox"
              />
              <span
                className={`todo-title ${todo.completed ? 'completed' : ''}`}
              >
                {todo.title}
              </span>
              <button
                onClick={() => deleteTodo(todo.id)}
                className="delete-button"
              >
                Delete
              </button>
            </div>
          ))
        )}
      </div>

      <div className="stats">
        <span>{todos.filter((t) => !t.completed).length} remaining</span>
        <span>{todos.length} total</span>
      </div>
    </div>
  );
}

export default App;
